jobs:
  - type: spider
    parameters:
      url: "http://localhost:3000"
      maxDuration: 2

  - type: activeScan
    parameters:
      url: "http://localhost:3000"
      recurse: true
      maxDuration: 5

  - type: report
    parameters:
      template: traditional-html
      reportFile: zap_report.html
      reportTitle: "ZAP Scan Report"
