name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Desplegar en producción
        run: echo "Desplegando la aplicación..."
